// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_SZbkHNYURMp0Cydny0G177dEAt9Lihc',
    appId: '1:223716701144:web:4952e5b6acfe6a4ccdf8ad',
    messagingSenderId: '223716701144',
    projectId: 'hostel-management-system-4bf5b',
    authDomain: 'hostel-management-system-4bf5b.firebaseapp.com',
    storageBucket: 'hostel-management-system-4bf5b.appspot.com',
    measurementId: 'G-44KW6G6C9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2dAvYTSE5KN8RYdMI78XGtRMi8uJsbkc',
    appId: '1:223716701144:android:36f232591025b58fcdf8ad',
    messagingSenderId: '223716701144',
    projectId: 'hostel-management-system-4bf5b',
    storageBucket: 'hostel-management-system-4bf5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIIX88iMo5-K-e2AmRbY-9FC7JHA7qh8c',
    appId: '1:223716701144:ios:e333e1b0acf188ffcdf8ad',
    messagingSenderId: '223716701144',
    projectId: 'hostel-management-system-4bf5b',
    storageBucket: 'hostel-management-system-4bf5b.appspot.com',
    iosClientId: '223716701144-e3o4j7tl1lqofo4qtmboiitcug87jm5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.hm.hostelmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIIX88iMo5-K-e2AmRbY-9FC7JHA7qh8c',
    appId: '1:223716701144:ios:e333e1b0acf188ffcdf8ad',
    messagingSenderId: '223716701144',
    projectId: 'hostel-management-system-4bf5b',
    storageBucket: 'hostel-management-system-4bf5b.appspot.com',
    iosClientId: '223716701144-e3o4j7tl1lqofo4qtmboiitcug87jm5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.hm.hostelmanagement',
  );
}
